# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        coverimage: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [607, 368] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image

        imageproject: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [500, 350] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image

        workimage: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [650, 650] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image

        bannerimage: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [607, 387] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image

        aboutusimage: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [678, 450] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image

        circleimage: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [324, 365] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image
