vich_uploader:
    db_driver: orm

    mappings:
        project_image:
            uri_prefix: '/assets/img/project'
            upload_destination: '%kernel.project_dir%/public/assets/img/project'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

